- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.9.2
  hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-merge-conflict
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: flake8
      args: [--max-line-length=100, infrabin, tests]
    - id: sort-simple-yaml
